package com.jaypal.authapp.audit.domain;

public enum AuthAuditEvent {

    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,

    REGISTER,
    EMAIL_VERIFY,
    EMAIL_VERIFICATION_RESEND,

    OAUTH_LOGIN_SUCCESS,
    OAUTH_LOGIN_FAILURE,

    TOKEN_REFRESH,
    TOKEN_ROTATION,
    TOKEN_REVOKED,

    PASSWORD_CHANGE,
    FORGOT_PASSWORD_REQUEST,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_RESET_FAILURE,

    ACCOUNT_DISABLED
}
