package com.jaypal.authapp.domain.audit.entity;

public enum AuthAuditEvent {

    /* AUTHENTICATION */
    LOGIN,
    LOGOUT_SINGLE_SESSION,
    LOGOUT_ALL_SESSIONS,
    REGISTER,
    EMAIL_VERIFICATION,
    EMAIL_VERIFICATION_RESEND,
    OAUTH_LOGIN,

    /* TOKEN */
    TOKEN_ISSUED,
    TOKEN_REFRESH,
    TOKEN_REVOKED_SINGLE,
    TOKEN_REVOKED_ALL,
    TOKEN_INTROSPECTION,

    /* PASSWORD */
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,

    /* ACCOUNT */
    ACCOUNT_VIEWED_SELF,
    ACCOUNT_UPDATED_SELF,
    ACCOUNT_DISABLED_BY_ADMIN,
    ACCOUNT_DELETED_SELF,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,

    /* AUTHORIZATION */
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,
    ACCESS_DENIED,

    /* ADMIN */
    ADMIN_USER_CREATED,
    ADMIN_USER_UPDATED,
    ADMIN_USER_DELETED,
    ADMIN_USER_VIEWED,
    ADMIN_USER_LISTED,
    ADMIN_ROLE_MODIFIED,
    ADMIN_PERMISSION_MODIFIED,
    ADMIN_ACTION_GENERIC,

    /* SYSTEM */
    RATE_LIMIT_EXCEEDED,
    SECURITY_POLICY_VIOLATION,
    SYSTEM_ERROR
}
