package com.jaypal.authapp.domain.audit.entity;

public enum AuthAuditEvent {

    /* AUTHENTICATION */
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT_SINGLE_SESSION,
    LOGOUT_ALL_SESSIONS,
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
    EMAIL_VERIFICATION_SUCCESS,
    EMAIL_VERIFICATION_FAILURE,
    EMAIL_VERIFICATION_RESEND,
    OAUTH_LOGIN_SUCCESS,
    OAUTH_LOGIN_FAILURE,

    /* TOKEN */
    TOKEN_ISSUED,
    TOKEN_REFRESH_SUCCESS,
    TOKEN_REFRESH_FAILURE,
    TOKEN_REVOKED_SINGLE,
    TOKEN_REVOKED_ALL,
    TOKEN_INTROSPECTION_SUCCESS,
    TOKEN_INTROSPECTION_FAILURE,

    /* PASSWORD */
    PASSWORD_CHANGE_SUCCESS,
    PASSWORD_CHANGE_FAILURE,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_REQUEST_FAILED,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_RESET_FAILURE,

    /* ACCOUNT */
    ACCOUNT_VIEWED_SELF,
    ACCOUNT_UPDATED_SELF,
    ACCOUNT_DISABLED_BY_ADMIN,
    ACCOUNT_DELETED_SELF,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,

    /* AUTHORIZATION */
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,
    // Emitted only by security filter, never by controllers
    ACCESS_DENIED,


    /* ADMIN */
    ADMIN_USER_CREATED,
    ADMIN_USER_UPDATED,
    ADMIN_USER_DELETED,
    ADMIN_USER_VIEWED,
    ADMIN_USER_LISTED,
    ADMIN_ROLE_MODIFIED,
    ADMIN_PERMISSION_MODIFIED,
    ADMIN_ACTION_GENERIC,

    /* SYSTEM */
    RATE_LIMIT_EXCEEDED,
    SECURITY_POLICY_VIOLATION,
    SYSTEM_ERROR
}
